### ISSUE TITLE
Webpage a little bit confusing

### ISSUE THREAD

**Issue by WweiL** [uchicago-cs/cmsc23320#1]
I and some of my friends all feel that the webpage is a little bit confusing -- we sometimes have difficulties finding some pages. I am thinking that maybe the course staffs are too familiar with the content to sense it. So I was thinking maybe I as someone who still has the confusion might propose some changes that are helpful.

The changes I'm thinking of are:

1. Add hyperlinks to projects in the calendar.
2. Remoe navbar - projects - project specifications. Spllit [that page](https://uchicago-cs.github.io/cmsc23320/projects/specs.html)  into 3, each with name project_i-intro.html, and add each to navbar - projects - project_i-intro.
3. Also add project_i-rubics, project_i-tips, project_i specifications to the navbar, so it will be looking like:
```
projects -
    - getting started
    - registering
    - project_1 intro
    - project_1 specifications
    - project_1 tips
    - project_1 rubics
    - project_2 intro
    - ...
```
4. Add [samples page](https://github.com/uchicago-cs/cmsc23320/tree/master/samples) to the resources navbar.

All don't seem to be of much code changes -- mostly file moves. If the course staff are fine with the change I could start to make pull requests.

**Comment by borjasotomayor** [comment]
Thanks for suggesting these changes. We have pushed an updated version of the website to branch website-reorg that incorporates these changes, except the Projects menu only includes one entry per project (otherwise, that menu will become too cluttered). You can see the exact changes in c836494, and can see a preview of what the updated website looks like here: http://people.cs.uchicago.edu/~borja/cmsc23320/ (we have not yet published these changes to the public website). Please let us know if these changes look good, or if you have additional feedback/suggestions.

**Comment by borjasotomayor** [comment]
Closing this issue since these changes have been incorporated into the public website.

**Comment by WweiL** [comment]
Thank you so much for the update! I'm really sorry I didn't see this before, the emails from github was buried with other updates. I think that looks much much better now!
